version: '3.1'
services:

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis_pw
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=abf
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  #migrate:
    #build:
      #context: ../..
      #ockerfile: Dockerfile
    #command: sh -c "/wait && /app/migrate"
    #environment:
      #- WAIT_HOSTS=db:5432
      #- WAIT_BEFORE_HOSTS=2
      #- DB_USERNAME=abf
      #- DB_PASSWORD=admin
      #- DB_HOST=db
    #depends_on: [db]