// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/abf.proto

package server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba96073bb84cdedc, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AuthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba96073bb84cdedc, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ResetRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba96073bb84cdedc, []int{2}
}

func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

func (m *ResetRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ResetRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AddNetMaskRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask                 string   `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNetMaskRequest) Reset()         { *m = AddNetMaskRequest{} }
func (m *AddNetMaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddNetMaskRequest) ProtoMessage()    {}
func (*AddNetMaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba96073bb84cdedc, []int{3}
}

func (m *AddNetMaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNetMaskRequest.Unmarshal(m, b)
}
func (m *AddNetMaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNetMaskRequest.Marshal(b, m, deterministic)
}
func (m *AddNetMaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNetMaskRequest.Merge(m, src)
}
func (m *AddNetMaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddNetMaskRequest.Size(m)
}
func (m *AddNetMaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNetMaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNetMaskRequest proto.InternalMessageInfo

func (m *AddNetMaskRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddNetMaskRequest) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

type AddNetMaskResponse struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask                 string   `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNetMaskResponse) Reset()         { *m = AddNetMaskResponse{} }
func (m *AddNetMaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddNetMaskResponse) ProtoMessage()    {}
func (*AddNetMaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba96073bb84cdedc, []int{4}
}

func (m *AddNetMaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNetMaskResponse.Unmarshal(m, b)
}
func (m *AddNetMaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNetMaskResponse.Marshal(b, m, deterministic)
}
func (m *AddNetMaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNetMaskResponse.Merge(m, src)
}
func (m *AddNetMaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddNetMaskResponse.Size(m)
}
func (m *AddNetMaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNetMaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNetMaskResponse proto.InternalMessageInfo

func (m *AddNetMaskResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddNetMaskResponse) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

type RemoveNetMaskRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask                 string   `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNetMaskRequest) Reset()         { *m = RemoveNetMaskRequest{} }
func (m *RemoveNetMaskRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNetMaskRequest) ProtoMessage()    {}
func (*RemoveNetMaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba96073bb84cdedc, []int{5}
}

func (m *RemoveNetMaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNetMaskRequest.Unmarshal(m, b)
}
func (m *RemoveNetMaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNetMaskRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNetMaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNetMaskRequest.Merge(m, src)
}
func (m *RemoveNetMaskRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNetMaskRequest.Size(m)
}
func (m *RemoveNetMaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNetMaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNetMaskRequest proto.InternalMessageInfo

func (m *RemoveNetMaskRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RemoveNetMaskRequest) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "abforce.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "abforce.AuthResponse")
	proto.RegisterType((*ResetRequest)(nil), "abforce.ResetRequest")
	proto.RegisterType((*AddNetMaskRequest)(nil), "abforce.AddNetMaskRequest")
	proto.RegisterType((*AddNetMaskResponse)(nil), "abforce.AddNetMaskResponse")
	proto.RegisterType((*RemoveNetMaskRequest)(nil), "abforce.RemoveNetMaskRequest")
}

func init() { proto.RegisterFile("api/abf.proto", fileDescriptor_ba96073bb84cdedc) }

var fileDescriptor_ba96073bb84cdedc = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x51, 0x5f, 0x4b, 0x3a, 0x41,
	0x14, 0xd5, 0x55, 0x7f, 0x3f, 0xbb, 0x9a, 0xd0, 0x64, 0x21, 0x2b, 0x45, 0xec, 0x53, 0x4f, 0x2b,
	0x14, 0x91, 0xd4, 0xd3, 0x0a, 0xf5, 0x52, 0x59, 0x2c, 0x41, 0xd0, 0xdb, 0xac, 0x7b, 0xd5, 0x65,
	0x5d, 0x67, 0x9a, 0x99, 0x35, 0xfa, 0x66, 0x7d, 0xbc, 0x70, 0x46, 0xdd, 0xc5, 0x82, 0xfe, 0xe0,
	0xdb, 0xcc, 0x3d, 0xe7, 0x9e, 0x7b, 0x38, 0x07, 0xb6, 0x29, 0x8f, 0x3a, 0x34, 0x18, 0xba, 0x5c,
	0x30, 0xc5, 0xc8, 0x7f, 0x1a, 0x0c, 0x99, 0x18, 0xa0, 0xdd, 0x1e, 0x31, 0x36, 0x9a, 0x60, 0x47,
	0x8f, 0x83, 0x74, 0xd8, 0xc1, 0x84, 0xab, 0x37, 0xc3, 0x72, 0xee, 0xa1, 0xe6, 0xa5, 0x6a, 0xec,
	0xe3, 0x4b, 0x8a, 0x52, 0x91, 0x26, 0x54, 0x26, 0x6c, 0x14, 0x4d, 0x5b, 0xc5, 0xa3, 0xe2, 0xf1,
	0x96, 0x6f, 0x3e, 0xc4, 0x86, 0x2a, 0xa7, 0x52, 0xbe, 0x32, 0x11, 0xb6, 0x2c, 0x0d, 0xac, 0xfe,
	0xa4, 0x01, 0x56, 0xc4, 0x5b, 0x25, 0x3d, 0xb5, 0x22, 0xee, 0x1c, 0x42, 0xdd, 0x08, 0x4a, 0xce,
	0xa6, 0x12, 0xe7, 0x38, 0x8b, 0xb5, 0x5c, 0xd5, 0xb7, 0x58, 0xec, 0x3c, 0x40, 0xdd, 0x47, 0x89,
	0x6a, 0x73, 0x17, 0xcf, 0x61, 0xc7, 0x0b, 0xc3, 0x3e, 0xaa, 0x3b, 0x2a, 0xe3, 0xa5, 0xac, 0x21,
	0x15, 0x97, 0x24, 0x42, 0xa0, 0x9c, 0x50, 0x19, 0x2f, 0xc4, 0xf4, 0xdb, 0xe9, 0x02, 0xc9, 0x2f,
	0x66, 0x86, 0xbf, 0xdd, 0xbc, 0x80, 0xa6, 0x8f, 0x09, 0x9b, 0xe1, 0xef, 0xaf, 0x9e, 0xbc, 0x97,
	0xa0, 0xe6, 0xf5, 0x44, 0xaa, 0x50, 0xd7, 0x43, 0xce, 0xa0, 0x3c, 0x0f, 0x8c, 0x34, 0xdd, 0x45,
	0x61, 0x6e, 0xae, 0x10, 0x7b, 0x6f, 0x6d, 0x6a, 0x4c, 0x3a, 0x05, 0xd2, 0x85, 0x8a, 0xce, 0x91,
	0x64, 0x8c, 0x7c, 0xae, 0xf6, 0xbe, 0x6b, 0x6a, 0x77, 0x97, 0xb5, 0xbb, 0x57, 0xf3, 0xda, 0x9d,
	0x02, 0xb9, 0x81, 0x86, 0x17, 0x86, 0x8f, 0xec, 0x69, 0x1c, 0x29, 0xbc, 0x8d, 0xa4, 0x22, 0x76,
	0x76, 0x64, 0x3d, 0x48, 0xbb, 0xfd, 0x25, 0xb6, 0xb2, 0xd1, 0x87, 0x5d, 0x93, 0xc4, 0xb5, 0x60,
	0x49, 0xa6, 0x78, 0x90, 0x33, 0xf5, 0x39, 0xa7, 0x1f, 0x98, 0xeb, 0x4d, 0xe8, 0x20, 0xde, 0xa8,
	0xb9, 0x4c, 0xf1, 0xaf, 0xe6, 0x7a, 0xf0, 0x5c, 0x75, 0x2f, 0x25, 0x8a, 0x19, 0x8a, 0xe0, 0x9f,
	0x46, 0x4f, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x9d, 0x04, 0xd5, 0x76, 0x03, 0x00, 0x00,
}
